### ISSUE TITLE
Is it possible to release a version that works with 5.0

### ISSUE THREAD

**Issue by Plume-yu** [VenoMKO/RE-Helper-Plugin#2]
Is it okay to release a version suitable for the new mood?

**Comment by VenoMKO** [comment]
@Plume-yu , I no longer support the project since Tera is dead.
Feel free to update or change the plugin as you see fit.

**Comment by Plume-yu** [comment]
I am currently learning UE5 and have not yet learned how to create plugins. Can you update this plugin to version 5.0 or higher
